receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  attributes:
    actions:
      # Add a custom attribute to store the request body (if captured upstream by SDKs).
      - key: http.request.body
        action: insert
        value: ""

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"


service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug,otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]